# SECURITY
efc_back_office_security_login:
    path:     /login
    defaults: { _controller: EfcBackOfficeBundle:Security:login }

efc_back_office_security_check:
    path:     /login-check
    defaults: { _controller: EfcBackOfficeBundle:Security:check }
    requirements:
        _method: POST

efc_back_office_security_logout:
    path:     /logout
    defaults: { _controller: EfcBackOfficeBundle:Security:logout }

# BACKOFFICE HOME
efc_back_office_homepage:
    path:     /
    defaults: { _controller: EfcBackOfficeBundle:Article:index }
    
# Article
efc_back_office_article_index:
    path:     /article
    defaults: { _controller: EfcBackOfficeBundle:Article:index }
    methods: [GET]

efc_back_office_article_view:
    path: /voir-article/{id}
    defaults: { _controller: EfcBackOfficeBundle:Article:view }
    methods: [GET]
    requirements:
        id: "\d+"

efc_back_office_article_create:
    path: /creer-article
    defaults: { _controller: EfcBackOfficeBundle:Article:create }
    methods: [GET, POST]

efc_back_office_article_edit:
    path: /editer-article/{id}
    defaults: { _controller: EfcBackOfficeBundle:Article:edit }
    methods: [GET, POST]
    requirements:
        id: "\d+"

efc_back_office_article_delete:
    path: /supprimer-article/{id}
    defaults: { _controller: EfcBackOfficeBundle:Article:delete }
    methods: [GET, POST]
    requirements:
        id: "\d+"
