# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern:            ^/admin
            form_login:
                provider:       fos_userbundle
                login_path:     efc_back_office_security_login
                use_forward:    true
                use_referer:    true
                check_path:     efc_back_office_security_check
                failure_path:   efc_back_office_security_login
                default_target_path: efc_back_office_homepage
            logout:
                path: efc_back_office_security_logout
                target: efc_cms_homepage
            anonymous:    true

    access_control:
            # back-office
            - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }